version: "3.3"

x-redis-common: &redis-common
  image: redis:latest
  command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
  healthcheck:
    test: [ "CMD", "redis-cli", "-p", "6379", "cluster", "info" ]
    interval: 1s
    timeout: 3s
    retries: 30

  redis1:
    <<: *redis-common
    ports:
      - "6371:6379"
  redis2:
    <<: *redis-common
    ports:
      - "6372:6379"
  redis3:
    <<: *redis-common
    ports:
      - "6373:6379"
  redis4:
    <<: *redis-common
    ports:
      - "6374:6379"
  redis5:
    <<: *redis-common
    ports:
      - "6375:6379"
  redis6:
    <<: *redis-common
    ports:
      - "6376:6379"
  
  redis-cluster-creator:
    image: redis
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create redis1:6379 redis2:6379 redis3:6379 redis4:6379 redis5:6379 redis6:6379 --cluster-replicas 1']
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
